# Project information
site_name: pypi-project-hardik
# defeine TOC or order of website-
nav:
  - Home: index.md
  - API Reference: APIreference.md

site_author: Hardik Seth
site_description: >-
  A library for rendering YouTube and reference sites in Jupyter notebooks and mainly to understand CI-CD in devlopment lifecycle.

# Repository
repo_name: sethhardik/pypi-project-hardik
repo_url: https://github.com/sethhardik/pypi-project-hardik

# Configuration
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime    
  # logo: PyTorch_logo_icon.svg
  
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/sethhardik
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/hardik-seth-b2a23b164

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js #?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  
  
plugins:
  - search

copyright: |
  &copy; 2023 <a href="https://github.com/sethhardik"  target="_blank" rel="noopener">Hardik Seth</a>